apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtl-app
  namespace: argocd
spec:
  destination:
    namespace: mtl-app
    server: 'https://kubernetes.default.svc'
  source:
    path: mtl-app
    repoURL: 'https://github.com/G4MBLERs/mtl-devops-exercise.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true