name: Docker Image build and publish

on:
  pull_request:
    branches: [ "main" ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.7

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "http://localhost:9000"        

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v


